export const GET_ALL_BATCH_REQUEST = "GET_ALL_BATCH_REQUEST";
export const GET_ALL_BATCH_SUCCESS = "GET_ALL_BATCH_SUCCESS";
export const GET_ALL_BATCH_FAILURE = "GET_ALL_BATCH_FAILURE";

export const SET_RAWMATERIAL_ID_BATCH = "SET_RAWMATERIAL_ID_BATCH";
