export const GET_ALL_MATERIAL_REQUEST = "GET_ALL_MATERIAL_REQUEST";
export const GET_ALL_MATERIAL_SUCCESS = "GET_ALL_MATERIAL_SUCCESS";
export const GET_ALL_MATERIAL_FAILURE = "GET_ALL_MATERIAL_FAILURE";

export const GET_ALL_MATERIAL_BYCATEID_REQUEST =
  "GET_ALL_MATERIAL_BYCATEID_REQUEST";
export const GET_ALL_MATERIAL_BYCATEID_SUCCESS =
  "GET_ALL_MATERIAL_BYCATEID_SUCCESS";
export const GET_ALL_MATERIAL_BYCATEID_FAILURE =
  "GET_ALL_MATERIAL_BYCATEID_FAILURE";
