export const GET_ALL_PO_REQUEST = "GET_ALL_PO_REQUEST";
export const GET_ALL_PO_SUCCESS = "GET_ALL_PO_SUCCESS";
export const GET_ALL_PO_FAILURE = "GET_ALL_PO_FAILURE";

export const UPDATE_PO_REQUEST = "UPDATE_PO_REQUEST";
export const UPDATE_PO_SUCCESS = "UPDATE_PO_SUCCESS";
export const UPDATE_PO_FAILURE = "UPDATE_PO_FAILURE";
